version: "3.8"
services:

  config-service:
    container_name: config-service
    image: mauriciovg/config-service:latest
    ports:
      - "8081:8081"

  mysql-db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=empleados
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 33061:3306

  eureka-service:
    container_name: eureka-service
    image: mauriciovg/eureka-service:latest
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    links:
      - config-service
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - spring.config.import=optional:configserver:http://config-service:8081
  gateway-service:
    container_name: gateway-service
    image: mauriciovg/gateway-service:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - spring.config.import=optional:configserver:http://config-service:8081
      - EUREKA_URL=http://eureka-service:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - config-service
      - eureka-service
    links:
      - config-service
      - eureka-service
  employee-service:
    container_name: employee-service
    image: mauriciovg/employee-service:latest
    ports:
      - "31231:8090"
    environment:
      - spring.config.import=optional:configserver:http://config-service:8081
      - EUREKA_URL=http://eureka-service:8761/eureka/
      - DB_URL=jdbc:mysql://mysql-db:3306/employees?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    deploy:
        restart_policy:
          condition: on-failure
    depends_on:
      - config-service
      - eureka-service
    links:
      - config-service
      - eureka-service
  clock-service:
    container_name: clock-service
    image: mauriciovg/clock-service:latest
    ports:
      - "31235:8091"
    environment:
      - spring.config.import=optional:configserver:http://config-service:8081
      - EUREKA_URL=http://eureka-service:8761/eureka/
      - DB_URL=jdbc:mysql://mysql-db:3306/clocks?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    deploy:
        restart_policy:
          condition: on-failure
    depends_on:
      - config-service
      - eureka-service
    links:
      - config-service
      - eureka-service
  justificativo-service:
    container_name: justificativo-service
    image: mauriciovg/justificativo-service:latest
    ports:
      - "31438:8092"
    environment:
      - spring.config.import=optional:configserver:http://config-service:8081
      - EUREKA_URL=http://eureka-service:8761/eureka/
      - DB_URL=jdbc:mysql://mysql-db:3306/justificativos?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    deploy:
        restart_policy:
          condition: on-failure
    depends_on:
      - config-service
      - eureka-service
    links:
      - config-service
      - eureka-service
  solicitud-service:
    container_name: solicitud-service
    image: mauriciovg/solicitud-service:latest
    ports:
      - "31239:8093"
    environment:
      - spring.config.import=optional:configserver:http://config-service:8081
      - EUREKA_URL=http://eureka-service:8761/eureka/
      - DB_URL=jdbc:mysql://mysql-db:3306/solicitudes?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    deploy:
        restart_policy:
          condition: on-failure
    depends_on:
      - config-service
      - eureka-service
    links:
      - config-service
      - eureka-service
  sueldo-service:
    container_name: sueldo-service
    image: mauriciovg/sueldo-service:latest
    ports:
      - "31238:8094"
    environment:
      - spring.config.import=optional:configserver:http://config-service:8081
      - EUREKA_URL=http://eureka-service:8761/eureka/
      - DB_URL=jdbc:mysql://mysql-db:3306/sueldos?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    deploy:
        restart_policy:
          condition: on-failure
    depends_on:
      - config-service
      - eureka-service
    links:
      - config-service
      - eureka-service

  frontend-service:
    container_name: frontend-service
    image: mauriciovg/frontend-service:latest
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
volumes:
  mysql-data:
