server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/MauricioValdesG/microsevices-data-project
          search-paths: config-data
          skip-ssl-validation: true
  application:
    name: config-service
