CREATE DATABASE IF NOT EXISTS `employees`;
CREATE DATABASE IF NOT EXISTS `clocks`;
CREATE DATABASE IF NOT EXISTS `justificativos`;
CREATE DATABASE IF NOT EXISTS `solicitudes`;
CREATE DATABASE IF NOT EXISTS `sueldos`;